version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
    working_directory: ~/TreasureMap

    steps:
      - checkout:
          path: ~/TreasureMap
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_PASSWORD: user_password
          MYSQL_DATABASE: webapp_test
          MYSQL_USER: user_name
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/TreasureMap
    steps:
      - checkout:
          path: ~/TreasureMap
      - ruby/install-deps
      - run:
          name: Databese setup
          command: bundle exec rake db:migrate
      - run:
          name: yarn Install
          command: yarn install
      - run: bundle exec bin/webpack

      - run:
          name: RSpec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/models/users_spec.rb" | \
              circleci tests split --split-by=timings)"
            bundle exec rspec \
              --format progress \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

  deploy:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
      - image: circleci/mysql:5.7
      - image: buildpack-deps:trusty
        environment:
          MYSQL_PASSWORD: user_password
          MYSQL_DATABASE: webapp_production
          MYSQL_USER: user_name
    steps:
      - checkout

      - run:
          name: Execute Heroku maintenance on
          command: heroku maintenance:on --app ${HEROKU_APP_NAME}
      - run:
          name: Heroku への main のデプロイ
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
      - run:
          name: Execute Heroku db migrate
          command: heroku run rails db:migrate --app ${HEROKU_APP_NAME}
      - run:
          name: Execut Heroku maintenance off
          command: heroku maintenance:off --app ${HEROKU_APP_NAME}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main